[package]
name = "mess"
version = "0.0.1-placeholder"
edition = "2021"
authors = ["Bob <bob@standardinput.co>"]
description = "placeholder for a prototype message storage lib"
repository = "https://github.com/bobisme/mess"
homepage = "https://github.com/bobisme/mess"
documentation = "https://github.com/bobisme/mess"
readme = "README.md"
license = "WTFPL"

[workspace]
members = ["xtask"]

[lib]
name = "mess"

[dependencies]
ident = { git = "https://github.com/bobisme/ident" }
once_cell = "1.18.0"
serde = "1.0.175"
serde_json = "1.0.103"
sqlx = { version = "0.7.1", features = ["macros", "sqlite"] }
thiserror = "1.0.44"
tracing = "0.1.37"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes"] }
rstest = "0.18"
tracing-subscriber = { version = "^0.3.14", features = ["env-filter"] }
