condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
max_width = 80
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 30
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
