//! One-hop `Upcast<Prev>` trait, its transitive composition into
//! `UpcastsTo<Latest>`, and the [`event_versions!`](crate::event_versions)
//! macro that wires both together with dispatch on
//! `StoredEvent::schema_version`.
//!
//! Hand-rolled port of the shape `spikes/codec_bakeoff/src/upcaster.rs`
//! prototypes for a `#[derive(Event)]` macro to generate later: callers
//! write one `Upcast<Prev>` impl per version bump; `event_versions!`
//! composes them into `UpcastsTo<Latest>` plus a `decode_*` dispatcher.

/// One hop in a version chain: build `Self` (version N) from its immediate
/// predecessor `Prev` (version N-1). Implement one of these per version
/// bump; [`event_versions!`](crate::event_versions) composes them
/// transitively into [`UpcastsTo`].
pub trait Upcast<Prev> {
    /// Upcast `prev` (the older version) into `Self` (one version newer).
    fn upcast(prev: Prev) -> Self;
}

/// Transitive upcast from any version to the fixed `Latest` type for its
/// event. Generated by [`event_versions!`](crate::event_versions) by
/// composing [`Upcast`] impls pairwise — never hand-written directly.
pub trait UpcastsTo<Latest> {
    /// Walk this version's `Upcast` chain forward to `Latest`.
    fn upcast_to_latest(self) -> Latest;
}

/// Composes one-hop [`Upcast`] impls into transitive [`UpcastsTo`]`<Latest>`
/// impls: version N upcasts one hop to N+1, then delegates to N+1's
/// generated impl. The last version listed is `Latest` and gets the
/// identity impl. Called by
/// [`event_versions!`](crate::event_versions); not meant to be invoked
/// directly (hence the `__`-prefixed name).
#[macro_export]
#[doc(hidden)]
macro_rules! __mess_core_upcast_impls {
    ($latest:ty; $cur:ty, $next:ty $(, $rest:ty)*) => {
        impl $crate::codec::UpcastsTo<$latest> for $cur {
            fn upcast_to_latest(self) -> $latest {
                <$next as $crate::codec::Upcast<$cur>>::upcast(self)
                    .upcast_to_latest()
            }
        }
        $crate::__mess_core_upcast_impls!($latest; $next $(, $rest)*);
    };
    ($latest:ty; $cur:ty) => {
        impl $crate::codec::UpcastsTo<$latest> for $cur {
            fn upcast_to_latest(self) -> $latest {
                self
            }
        }
    };
}

/// Declares a versioned event's upcast chain and generates a `decode_*`
/// dispatcher.
///
/// Given `versions: [1 => V1, 2 => V2, 3 => V3]` and one hand-written
/// `impl Upcast<Prev> for Next` per hop, generates:
///  - transitive `UpcastsTo<V3>` impls for `V1` and `V2` (identity for
///    `V3` itself),
///  - `pub fn decode_fn(&StoredEvent) -> Result<V3, UpcastError>` that
///    checks `event_name`, decodes the payload as the version named by
///    `schema_version`, and upcasts to `V3` — or fails loudly with
///    [`UpcastError::WrongEventName`](crate::codec::UpcastError::WrongEventName),
///    [`UpcastError::UnknownSchemaVersion`](crate::codec::UpcastError::UnknownSchemaVersion),
///    or [`UpcastError::Codec`](crate::codec::UpcastError::Codec).
///
/// This is the hand-rolled shape a `#[derive(Event)]` /
/// `#[event(version = N)]` macro generates; see
/// `spikes/codec_bakeoff/src/upcaster.rs`.
#[macro_export]
macro_rules! event_versions {
    (
        name: $event_name:literal,
        latest: $latest:ty,
        versions: [ $( $ver:literal => $ty:ty ),+ $(,)? ],
        decode_fn: $decode_fn:ident
    ) => {
        $crate::__mess_core_upcast_impls!($latest; $($ty),+);

        pub fn $decode_fn(
            ev: &$crate::codec::StoredEvent,
        ) -> ::std::result::Result<$latest, $crate::codec::UpcastError> {
            if ev.event_name != $event_name {
                return ::std::result::Result::Err(
                    $crate::codec::UpcastError::WrongEventName {
                        expected: $event_name,
                        got: ev.event_name.clone(),
                    },
                );
            }
            match ev.schema_version {
                $(
                    $ver => {
                        let v: $ty = ev.decode()?;
                        ::std::result::Result::Ok(
                            $crate::codec::UpcastsTo::upcast_to_latest(v),
                        )
                    }
                )+
                other => ::std::result::Result::Err(
                    $crate::codec::UpcastError::UnknownSchemaVersion {
                        event_name: ev.event_name.clone(),
                        version: other,
                        known_versions: &[$($ver),+],
                    },
                ),
            }
        }
    };
}
