[package]
name = "mess-store"
version = "0.0.0"
edition = "2024"
description = "mess v1: EventStore API surface"

[dependencies]
mess-core = { workspace = true }
quick_cache = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
