[package]
name = "mess-derive"
version = "0.0.0"
edition = "2024"
description = "mess v1: proc-macros"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }

[dev-dependencies]
mess-core = { workspace = true }
serde = { version = "1", features = ["derive"] }
trybuild = "1"
